# Generated by Django 5.0 on 2023-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Required. please enter a valid email address.",
                max_length=254,
                verbose_name="email address",
            ),
        ),
    ]
