# Generated by Django 5.0 on 2023-12-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_city_options_alter_home_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "physical_id",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        unique=True,
                        verbose_name="Physical id of Controller",
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional user defined name for a controller",
                        max_length=128,
                        null=True,
                        verbose_name="Controller name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Activation status"
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False, verbose_name="Registration status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last update"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(verbose_name="Registration date"),
                ),
                (
                    "home_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.home"
                    ),
                ),
            ],
            options={
                "verbose_name": "Controller",
                "verbose_name_plural": "Controllers",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional user defined name for a controller",
                        max_length=128,
                        null=True,
                        verbose_name="Device name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Activation status"
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False, verbose_name="Registration status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last update"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(verbose_name="Registration date"),
                ),
                (
                    "controller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.controller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
    ]
