# Generated by Django 5.0 on 2023-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_controller_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controller",
            name="registered_at",
            field=models.DateTimeField(
                editable=False, verbose_name="Registration date"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="registered_at",
            field=models.DateTimeField(
                editable=False, verbose_name="Registration date"
            ),
        ),
    ]
