# Generated by Django 5.0 on 2023-12-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_controller_registered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="physical_id",
            field=models.CharField(
                db_index=True,
                default="123454266985",
                max_length=12,
                unique=True,
                verbose_name="Physical id of Device",
            ),
            preserve_default=False,
        ),
    ]
