# Generated by Django 5.0 on 2023-12-20 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_device_physical_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controller",
            old_name="home_id",
            new_name="home",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="controller_id",
            new_name="controller",
        ),
        migrations.RenameField(
            model_name="home",
            old_name="loc_id",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="home",
            old_name="User_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="city_id",
            new_name="city",
        ),
    ]
