# Generated by Django 5.0 on 2023-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_home_id_controller_home_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="alias_name",
            field=models.CharField(
                blank=True,
                help_text="Optional user defined name for a home",
                max_length=128,
                null=True,
                verbose_name="Home name",
            ),
        ),
    ]
