# Generated by Django 5.0 on 2023-12-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_home_alias_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="is_manual",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
