# Generated by Django 5.0 on 2023-12-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_controller_is_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controller",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.home",
            ),
        ),
    ]
