# Generated by Django 5.0 on 2024-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_controller_registered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="is_register_pending",
            field=models.BooleanField(
                default=False, verbose_name="Registration pending"
            ),
        ),
    ]
