# Generated by Django 5.0 on 2024-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_controller_is_register_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controller",
            name="registered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Registration date"
            ),
        ),
    ]
