# Generated by Django 5.0 on 2024-02-27 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_controller_registered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsulationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=3,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(-50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="home",
            name="insulation_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.insulationlevel",
            ),
        ),
    ]
