# Generated by Django 5.0 on 2024-02-27 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_insulationlevel_home_insulation_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insulationlevel",
            options={
                "verbose_name": "Insulation Level",
                "verbose_name_plural": "Insulation Levels",
            },
        ),
    ]
