# Generated by Django 5.0 on 2024-02-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_insulationlevel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="insulationlevel",
            name="title",
            field=models.CharField(default="hello", max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
