# Generated by Django 5.0 on 2023-12-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_home_alias_name"),
        ("weather", "0002_alter_parameter_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional user defined name for a preference",
                        max_length=128,
                        null=True,
                        verbose_name="Preference Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference",
                "verbose_name_plural": "Preferences",
                "unique_together": {("user", "alias_name")},
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.parameter",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.preference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Configs",
            },
        ),
        migrations.CreateModel(
            name="WeatherCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_manual", models.BooleanField(blank=True, default=False)),
                (
                    "controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.controller",
                    ),
                ),
            ],
            options={
                "verbose_name": "WeatherCondition",
                "verbose_name_plural": "WeatherConditions",
            },
        ),
        migrations.CreateModel(
            name="ParameterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.parameter",
                    ),
                ),
                (
                    "weather_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.weathercondition",
                    ),
                ),
            ],
            options={
                "verbose_name": "ParameterValue",
                "verbose_name_plural": "ParameterValues",
            },
        ),
    ]
