# Generated by Django 5.0 on 2023-12-24 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_preference_config_weathercondition_parametervalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weathercondition",
            options={
                "verbose_name": "Weather Condition",
                "verbose_name_plural": "Weather Conditions",
            },
        ),
    ]
