# Generated by Django 5.0 on 2023-12-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_home_alias_name"),
        ("weather", "0004_alter_weathercondition_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathercondition",
            name="controller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.controller"
            ),
        ),
    ]
