# Generated by Django 5.0 on 2023-12-25 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0005_alter_weathercondition_controller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weathercondition",
            name="is_manual",
        ),
    ]
