# Generated by Django 5.0 on 2023-12-25 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_controller_is_manual"),
        ("weather", "0006_remove_weathercondition_is_manual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametervalue",
            options={
                "verbose_name": "Parameter Value",
                "verbose_name_plural": "Parameter Values",
            },
        ),
        migrations.CreateModel(
            name="ControllerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pending", models.BooleanField(blank=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "controller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.controller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controller Status",
                "verbose_name_plural": "Controller Statuses",
            },
        ),
        migrations.CreateModel(
            name="StatusValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "controllerstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.controllerstatus",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Value",
                "verbose_name_plural": "Status Values",
            },
        ),
    ]
