# Generated by Django 5.0 on 2023-12-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_controller_is_manual"),
        ("weather", "0010_alter_parametervalue_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathercondition",
            name="controller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_condition",
                to="home.controller",
            ),
        ),
    ]
