# Generated by Django 5.0 on 2023-12-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0012_preferencechoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferencechoice",
            name="impact",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(-50),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
