# Generated by Django 5.0 on 2023-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0013_alter_preferencechoice_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferencechoice",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="preferencechoice",
            unique_together={("title", "impact")},
        ),
    ]
