# Generated by Django 5.0 on 2023-12-28 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0016_alter_config_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="config",
            unique_together={("preference", "parameter", "value")},
        ),
    ]
