# Generated by Django 5.0 on 2023-12-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_controller_registered_at"),
        ("weather", "0018_alter_config_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllerstatus",
            name="controller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controller_status",
                to="home.controller",
            ),
        ),
    ]
